feat: configured user registration and authorization using jwt
Information-platform-about-IT-companies/Backend-main pull request #10
Opened 2023-11-04 11:50 UTC by aleksandrkomyagin

Настроил регистрацию и авторизацию пользователя с помощью JWT. Добавил отправку письма с ссылкой для подтверждения действия. Скорректировал валидацию пароля и модель User.

2023-11-04 18:16 UTC, NotMainCode requested changes
тестировать свой код перед открытием PR
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/23ac6ee1-abcc-40a8-9580-04e04d313d65)

![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/e71025e3-822b-49ba-9683-cd4802b62907)

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +from django.core.exceptions import ValidationError
удалить
согласно [соглашению](https://www.django-rest-framework.org/api-guide/exceptions/#validationerror) следует использовать `serializers.ValidationError`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        super().validate(attrs)
нет необходимости в вызове `super().validate(attrs)`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        uid = self.initial_data.get("uid")
нет необходимости в использовании функции словаря `get` - к моменту вызова метода `validate` значения обязательных полей сериализатора (в данном случае uid и token) уже точно есть в атрибуте `attrs`
вместо словаря `initial_data` следует использовать атрибут метода `attrs`
```
uid = attrs["uid"]
encode_token = attrs["token"]
```

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        user = User.objects.get(id=id)
метод [get](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#get) может вызвать исключение [Model.DoesNotExist](https://docs.djangoproject.com/en/4.2/ref/models/class/#django.db.models.Model.DoesNotExist)

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        id = int(force_str(urlsafe_base64_decode(uid)))
могут быть вызваны исключения ValueError, TypeError, OverflowError
строки 36 и 37 следует обернуть в try..except
```
        try:
            uid = decode_uid(data["uid"])
            self.user = User.objects.get(pk=uid)
        except (User.DoesNotExist, ValueError, TypeError, OverflowError):
            raise serializers.ValidationError(
                {"uid": "Неверный id или пользователь не существует."}
            )
```

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        if user:
с учётом комментария к строке 36 нет необходимости в этом условии

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +            return user if decode_token else None
метод `validate` должен возвращать словарь с валидными данными `attrs` - https://www.django-rest-framework.org/api-guide/serializers/#object-level-validation

для использования значения `user` во вьюхе можно добавить объекту сериализатора атрибут `user` переопределив метод `__init__` сериализатора
```
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None
```
присвоить значение
```
self.user = user
```
и использовать во вьюхе
```
user = serializer.user
```

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +            user = serializer.validated_data
см. комментарий к строке 40 `serializers.py`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +            return Response("Пользователь активирован", status=status.HTTP_201_CREATED)
в нашем случае в ответе должен быть передан словарь с aceess и refresh токенами, код ответа 200

код ответа 201 используется в случае успешного создания ресурса

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        ok_pass = self.initial_data["password"] == self.initial_data["re_password"]
нет необходимости в переменной `ok_pass`

вместо словаря `initial_data` следует использовать словарь `attrs`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        return super().validate(attrs)
нет необходимости в `super()...`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +validator = CustomPasswordValidator()
нет необходимости в этой переменной

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        else:
нет необходимости в `else`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +class CustomAuthModel(viewsets.ModelViewSet):
лучшее имя `AuthViewSet`

Вьюсет в данном случае избыточен, т.к. содержит только `action`, вместо вьюсета можно использовать FBV с декоратором `@api_view`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +    permission_classes = [IsReadOnly]
нет необходимости в параметре `permission_classes`, т.к. в каждом `action` переопределён этот параметр
или указать `permission_classes = (AllowAny,)` и убрать этот параметр из `action`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/permissions.py
> +    def has_object_permission(self, request, view, obj):
в данном случае нет необходимости в переопределении этого метода, т.к. `has_permission` пропустит только "безопасные запросы"
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/2177d9a3-b3ee-4389-a316-1951afcb4bf8)

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/permissions.py
> +class IsReadOnly(permissions.BasePermission):
нет необходимости в этом классе - см. комментарий к строке 36 `views.py`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        elif self.action == "reset_password_confirm":
нет необходимости в `elif`, т.к. к этому моменту уже все возможные варианты `action` перебраны - можно сразу `return UserResetPasswordConfirmSerializer`

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +            return UserSerializer
`UserSerializer` нигде не используется

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +from ..auth.serializers import (
заменить на абсолютный импорт

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +from ..auth.permissions import IsReadOnly
заменить на абсолютный импорт

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        permission_classes=(AllowAny,),
см. комментарий к строке 36

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        url_path="signup",
нет необходимости в этом параметре, т.к. URL совпадает с именем метода

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        if serializer.is_valid(raise_exception=True):
нет необходимости в условии и строке 87 (return на строке 87 никогда не сработает, если в метод `is_valid` передан параметр `raise_exception=True`)

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/urls.py
> +v1_router.register("", CustomAuthModel, basename="auth")
роутер в данном случае избыточен, т.к. генерирует множество эндпоинтов, которые не используются (см. комментарий к строке 34 `views.py`)

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/urls.py
> +app_name = "auth"
нет приложения `auth` - удалить

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +class UserSerializer(serializers.ModelSerializer):
класс не используется - удалить

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +    def validate(self, attrs):
также должна быть проверка - если `user.is_active=True`, то должен быть ответ 403 "User is active"
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/34434894-d90f-48ff-b2b3-51e14ad10cff)

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +            user = User.objects.get(email=email)
во вью следует использовать валидированные данные из словаря `serializer.validated_data'

2023-11-04 18:16 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        serializer = self.get_serializer(data=data)
в сериализаторе должны быть определены все необходимые поля, значение аргумента следует задавать так `data=request.data`

2023-11-06 13:18 UTC, aleksandrkomyagin commented on main/api/v1/auth/serializers.py
> +        ok_pass = self.initial_data["password"] == self.initial_data["re_password"]
Пароль не хранится в attrs.

2023-11-06 13:19 UTC, aleksandrkomyagin commented on main/api/v1/auth/serializers.py
> +validator = CustomPasswordValidator()
Чтобы вызвать метод validate, нужно создать экземпляр класса валидатора, чтобы автоматически подставлялся параметр self.

2023-11-08 01:05 UTC, NotMainCode requested changes
тестировать свой код перед отправкой на ревью

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        return Response(status=status.HTTP_400_BAD_REQUEST)
как понять почему не прошёл запрос?

![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/177127f2-aac2-45c9-9271-118a335d1e5e)

Во всех случаях с условием `if serializer.is_valid():` лучшим решением будет заменить это условие на `serializer.is_valid(raise_exception=True)` и удалить все `return...` аналогичные строке 79 во всех классах этого модуля.

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +                "На почту отправлено письмо со ссылкой подтверждения",
удалить во всех аналогичных случаях - ответ 204 не предполагает наличия тела ответа

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +            if user.is_active
при текущей реализации строки 85 и в случае передачи невалидных данных получаем:
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/23b152b1-6722-49cb-9da2-47d83190944c)

это условие во всех аналогичных случаях следует реализовать в соответствующих сериализаторах в виде:
```
    if self.user.is_active:
        raise PermissionDenied("User is active.") # или raise PermissionDenied("User is inactive.") 
```
импортировать
`from rest_framework.exceptions import PermissionDenied`

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        serializer = self.get_serializer(action)(data=request.data)
сейчас значением является объект класса `UserResetPasswordConfirmSerializer`

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +    email = serializers.CharField()
в методе `validate` необходимо реализовать проверку того, что пользователь существует с переданными email и password (аналогично строкам 78-85. В соответствующей вьюхе пользователь будет доступен как `serializer.user`

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        except (User.DoesNotExist, ValueError, TypeError, OverflowError):
тут возможно только одно исключение  - `User.DoesNotExist`

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        if value != self.initial_data["re_password"]:
при необходимости доступа к значениям нескольких полей следует реализовать метод `validate` и использовать словарь `attrs` вместо `initial_data`
https://www.django-rest-framework.org/api-guide/serializers/#object-level-validation

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        decode_token = default_token_generator.check_token(self.user, encode_token)
если токен невалиден, то необходимо поднимать `ValidationError` с сообщением, например "Некорректный токен или срок его действия истёк"

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        return attrs if decode_token else None
метод `validate` должен возвращать только словарь `attrs` с валидными данными

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        if value != self.initial_data["re_password"]:
при необходимости доступа к значениям нескольких полей следует реализовать метод `validate` и использовать словарь `attrs` вместо `initial_data`
https://www.django-rest-framework.org/api-guide/serializers/#object-level-validation

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +    def validate(self, attrs):
в методе должна быть валидация данных

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        ok_pass = self.initial_data["password"] == self.initial_data["re_password"]
сейчас password нет в attrs, потому что метод validate_password не возвращает `value`

методы валидации должны возвращать словарь с валидными данными

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        return validator.validate(value)
методы валидации должны возвращать словарь с валидными данными

исправить во всех аналогичных случаях

2023-11-08 01:05 UTC, NotMainCode commented on main/api/v1/auth/serializers.py
> +        ok_pass = (
нет необходимости в этой переменной
```
if attrs["new_password"] != attrs["re_new_password"]:
...
```

метод validate_new_password должен возвращать value

2023-11-08 01:35 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +from rest_framework_simplejwt import tokens
импортировать и использовать в соответствии с [документацией](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/creating_tokens_manually.html)

2023-11-11 13:21 UTC, NotMainCode requested changes

2023-11-11 13:21 UTC, NotMainCode commented on main/api/v1/auth/views.py
>                  "Пароль изменен",
удалить - ответ 204 не предполагает наличия тела ответа

2023-11-11 13:21 UTC, NotMainCode commented on main/api/v1/auth/views.py
> +        if serializer.is_valid(raise_exception=True):
https://www.django-rest-framework.org/api-guide/serializers/#raising-an-exception-on-invalid-data

[тут](https://github.com/Information-platform-about-IT-companies/Backend-main/pull/10#discussion_r1385554907) речь была о том, что нужно привести к виду:
```
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        confirm_url = self._generate_url(action, user, request)
        mail = self._generate_mail(action, confirm_url)
        user.send_mail(user, mail)
        return Response(
            status=status.HTTP_204_NO_CONTENT,
        )
```

исправить во всех аналогичных случаях

2023-11-11 13:21 UTC, NotMainCode commented on main/api/v1/auth/views.py
>              return Response(
согласно сегодняшнего созвона решено, что тут должен быть ответ 204 (без тела)

2023-11-11 13:21 UTC, NotMainCode commented on main/api/v1/auth/views.py
>              return Response(
согласно сегодняшнего созвона решено, что не будет 2FA и тут нужно передать access и refresh токены

2023-11-11 13:21 UTC, NotMainCode commented on main/api/v1/auth/views.py
>  class UserSigninConfirmView(BaseView, views.APIView):
согласно сегодняшнего созвона решено, что не будет 2FA - удалить этот класс

2023-11-11 13:21 UTC, NotMainCode commented on main/main/settings.py
> -    # {
удалить закоменченные строки

2023-11-11 13:21 UTC, NotMainCode commented on main/main/settings.py
> +PASSWORD_HASHERS = (
удалить - хэширование пароля будет по умолчанию

2023-11-11 13:21 UTC, NotMainCode commented on main/main/settings.py
> +MAX_LEN_PASSWORD_USER_MODEL: int = 80
вернуть как было - 30
валидация будет на стороне сервера

2023-11-11 13:21 UTC, NotMainCode commented on main/users/validators.py
> +    DEFAULT_USER_ATTRIBUTES = ("username", "first_name", "last_name", "email")
удалить все новые строки - нет таких требований к полю password в этом проекте

2023-11-11 13:21 UTC, NotMainCode commented on main/users/models.py
> +    validator = CustomPasswordValidator()
расположить после определения полей (до или после `objects = ...`

2023-11-11 15:42 UTC, aleksandrkomyagin commented on main/main/settings.py
> -    # {
Это из другого коммита. У меня сейчас нет коммента в этой строке

2023-11-11 15:46 UTC, aleksandrkomyagin commented on main/users/models.py
> +    validator = CustomPasswordValidator()
Так можно делать. Подсмотрел в базовом классе.
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/112546606/7a2cfde8-ee4b-4382-9103-f2ca17c4fef1)

2023-11-11 19:54 UTC, NotMainCode approved these changes

2023-11-11 22:01 UTC, closed without merging

2023-11-11 22:01 UTC, NotMainCode commented
Изменения в объединённом [PR](https://github.com/Information-platform-about-IT-companies/Backend-main/pull/13)