‘feat: endpoint companies filters and favorite’
Information-platform-about-IT-companies/Backend-main pull request #30
Opened 2023-11-14 21:06 UTC by olees-orlenko

2023-11-14 22:32 UTC, Stryukov approved these changes
Не криминально, но есть что улучшить. Если времени нет, то можно это оставить на рефакторинг в будущем.

2023-11-14 22:32 UTC, Stryukov commented on main/api/v1/companies/serializers.py
> +    def get_favorited(self, obj):
Твой код тоже рабочий, но еще посмотри на такое исполнение. Мой ревьюер в практикуме учил явно выделять логику. Т.е. смотри, сначала если пользователь аноним, то сразу отдаем False, так легче читать код, когда нету много вложенных return. А во втором случае возвращаем True если совпали оба условия. 
```
       if request.user.is_anonymous:
            return False

        return (
            FavoritesList.objects.filter(
                user=request.user, company=obj
            ).exists()
            and request.user.is_authenticated
        )
```

2023-11-14 22:32 UTC, Stryukov commented on main/api/v1/companies/serializers.py
> +    def to_representation(self, instance):
А зачем так? Можешь пояснить. Почему не подходит например вариант:
```
phones = Phone(
        many=True, source='company.number', required=False
    )
```

2023-11-14 22:32 UTC, Stryukov commented on main/api/v1/companies/views.py
> +        if user.is_anonymous:
А почему у нас в избранное может добавлять аноним? Я думаю нужно в пермишенах граничить только аторизованным и тогда в этом коде нет необходимости.

2023-11-14 22:32 UTC, Stryukov commented on main/api/v1/companies/views.py
> +            FavoritesList.objects.create(user=user, company=company)
окей, но я бы все сделал через сериализатор, чтобы там и валидировать. Например так:
```
        try:
            serializer = serializer(data=request.data)
            if serializer.is_valid():
                serializer.save(user=request.user, company=company)
                return Response(
                    serializer.data, status=status.HTTP_201_CREATED
                )
        except IntegrityError as error:
            return Response(
                {'errors': str(error)}, status=status.HTTP_400_BAD_REQUEST
            )
```

2023-11-14 22:32 UTC, Stryukov commented on main/api/v1/companies/views.py
> +            favoriteslist = FavoritesList.objects.filter(
Можно использовать метод get и отлавливать исключение DoesNotExist:
```
        try:
            instance = related_model.objects.get(
                company=company, user=request.user
            )
        except related_model.DoesNotExist as error:
            return Response(
                {'errors': str(error)}, status=status.HTTP_400_BAD_REQUEST
            )
```

2023-11-14 22:32 UTC, Stryukov commented on main/api/v1/companies/serializers.py
> +class CompanyFavoriteSerializer(serializers.ModelSerializer):
Не очень понял как у тебя работает этот сериалайзер. Почему у тебя внутри компании еще компания?

2023-11-14 22:32 UTC, Stryukov commented on main/companies/models.py
> +        related_name="favorite",
Я бы тут как-то по другому именовал, это же список пользователей у которых в избранном находится эта компания. Например, in_favorite

2023-11-14 22:32 UTC, Stryukov commented on main/companies/models.py
> +    number = models.CharField(max_length=18, null=True)
Можно добавить пустой номер? Такое есть в требованиях?

2023-11-15 14:21 UTC, olees-orlenko commented on main/api/v1/companies/serializers.py
> +    def to_representation(self, instance):
Это, чтобы вид был, как в доке: "phones": ["+79313692948", "+79313692904"]. Твой вариант выдает ошибку: TypeError: Phone() got unexpected keyword arguments: 'many', 'source', 'required'. А, если ты имел ввиду phones = PhoneSerializer(many=True, required=False), то выдает словарь  "number": "+79313692948". Я решила сделать, как в сваггере. Если нужен словарь, то переделаю.

2023-11-15 14:22 UTC, olees-orlenko commented on main/api/v1/companies/views.py
> +        if user.is_anonymous:
В избранное аноним не может добавить, может только компании просматривать.

2023-11-15 14:43 UTC, olees-orlenko commented on main/api/v1/companies/serializers.py
> +class CompanyFavoriteSerializer(serializers.ModelSerializer):
На самом деле, можно и вообще убрать этот сериалайзер, в пост-запросе вьюз оставить CompanySerializer. Будет только разница в выдаче полей. Если она нам неважна... Ааа, похоже, что ответа не должно быть, тогда убираю.

2023-11-15 14:50 UTC, olees-orlenko commented on main/api/v1/companies/views.py
> +            FavoritesList.objects.create(user=user, company=company)
я пока не стала менять.

2023-11-15 14:50 UTC, olees-orlenko commented on main/api/v1/companies/views.py
> +            favoriteslist = FavoritesList.objects.filter(
это тоже пока не стала менять.

2023-11-15 14:52 UTC, NotMainCode requested changes

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
> +        if request and not request.user.is_anonymous:
вместо `is_anonymous` следует использовать атрибут `is_authenticated`
https://docs.djangoproject.com/en/4.2/ref/contrib/auth/#attributes

в случае проверки и возврата `bool` значений правильно так:
```
    return (
        not request.user.is_authenticated
        or FavoritesList.objects.filter(user=request.user, company=obj).exists()
    )
```

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
> +        request = self.context.get("request")
нет необходимости использовать метод `get` и проверку `if request`, т.к. `request` точно есть в словаре `context`
`request = self.context["request"]`

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
> +    is_favorited = serializers.SerializerMethodField(method_name="get_favorited")
зачем переопределять имя метода ?

`def get_is_favorited...`

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
> +    def to_representation(self, instance):
нет необходимости переопределять этот метод - поле `phones` есть у объектов `Company` благодаря `related_name`
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/efa556e2-bf30-4ee2-9c80-ce2fc8df1a44)

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
>      class Meta:
класс `Meta` расположить перед методами сериализатора

2023-11-15 14:52 UTC, NotMainCode commented on main/companies/logo/favicon-32x32.png
этого файла не должно быть тут и не должно быть в репозитории
файлы лого компаний располагаются согласно значению `MEDIA_ROOT` и значению параметра `upload_to`  поля `logo` модели `Company` - `media/companies/logo`

2023-11-15 14:52 UTC, NotMainCode commented on main/companies/logo/favicon-32x32_5uQZTsa.png
этого файла не должно быть тут и не должно быть в репозитории
файлы лого компаний располагаются согласно значению `MEDIA_ROOT` и значению параметра `upload_to`  поля `logo` модели `Company` - `media/companies/logo`

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/views.py
> +        if user.is_anonymous:
удалить - это должно регулироваться пермишеном

2023-11-15 14:52 UTC, NotMainCode commented on main/api/v1/companies/views.py
>      permission_classes = (AllowAny,)
пермишены определить в методе `get_permissions` в зависимости от того вызывается метод `favotite` или нет

2023-11-15 14:52 UTC, NotMainCode commented on main/companies/models.py
> +class FavoritesList(models.Model):
лучше `Favorite`

2023-11-15 14:52 UTC, NotMainCode commented on main/companies/models.py
> +    number = models.CharField(max_length=18, null=True)
чтобы строковое поле сделать необязательным следует использовать `blank=True`
https://docs.djangoproject.com/en/4.2/ref/models/fields/#null

2023-11-15 14:54 UTC, olees-orlenko commented on main/companies/models.py
> +    number = models.CharField(max_length=18, null=True)
Это я видимо забыла убрать, когда с миграциями и своей бд боролась.)))

2023-11-15 15:23 UTC, olees-orlenko commented on main/api/v1/companies/serializers.py
> +    def get_favorited(self, obj):
сделала по-твоему, потом Олег прислал свои замечания и пришлось поменять так, как хотел он)))))

2023-11-15 15:38 UTC, olees-orlenko commented on main/api/v1/companies/serializers.py
> +    is_favorited = serializers.SerializerMethodField(method_name="get_favorited")
это же английский язык, так правильно! И метод я не переопределяла.

2023-11-15 15:43 UTC, olees-orlenko commented on main/api/v1/companies/serializers.py
> +    def to_representation(self, instance):
я его так сделала, чтобы в выдаче был список, а не словарь. Так у тебя в сваггере. Если нужен словарь, сделаю его, уберу этот метод.

2023-11-15 15:53 UTC, olees-orlenko commented on main/companies/models.py
> +class FavoritesList(models.Model):
кому лучше?

2023-11-15 15:54 UTC, olees-orlenko commented on main/companies/models.py
> +    number = models.CharField(max_length=18, null=True)
оно же вроде обязательное

2023-11-15 16:04 UTC, olees-orlenko commented on main/companies/models.py
> +class FavoritesList(models.Model):
Ради чего переделывать весь код?

2023-11-15 18:57 UTC, NotMainCode commented on main/companies/models.py
> +    number = models.CharField(max_length=18, null=True)
зачем тогда null=True ?

2023-11-15 18:58 UTC, NotMainCode commented on main/companies/models.py
> +class FavoritesList(models.Model):
https://techrocks.ru/2021/04/22/django-models-best-practices/

Eдиница модели (экземпляр класса) не содержит информацию о нескольких объектах сразу

2023-11-15 19:01 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
> +    def to_representation(self, instance):
ок, должен быть список

2023-11-15 19:03 UTC, NotMainCode commented on main/api/v1/companies/serializers.py
> +    is_favorited = serializers.SerializerMethodField(method_name="get_favorited")
method_name="get_favorited" - это есть переопределение имени метода, если без этого, то метод будет называться `def get_is_favorited...`
https://www.django-rest-framework.org/api-guide/fields/#serializermethodfield

2023-11-15 19:03 UTC, olees-orlenko commented on main/companies/models.py
> +    number = models.CharField(max_length=18, null=True)
забыла убрать, когда с миграциями и своей бд боролась.))) Уже убрала.

2023-11-15 19:11 UTC, NotMainCode approved these changes

2023-11-15 22:09 UTC, Stryukov commented on main/api/v1/companies/views.py
> +        if user.is_anonymous:
Окей, тогда помоему можно в action указать нужный для него пермишен. 
```
    @action(
        detail=True,
        methods=['post', 'delete'],
        permission_classes=(IsAuthenticated,)
    )
```

2023-11-17 19:02 UTC, closed without merging