Feature/model user
Information-platform-about-IT-companies/Backend-main pull request #4
Opened 2023-10-19 18:02 UTC by aleksandrkomyagin

Создал модель User. В файле setting.py добавил константу MAX_LENGHT_USER_MODEL для настройки длины полей модели User.

2023-10-19 21:44 UTC, NotMainCode requested changes
При переопределении модели пользователя необходимо задать соответствующее значение `AUTH_USER_MODEL` в `settings.py` https://docs.djangoproject.com/en/4.1/topics/auth/customizing/#substituting-a-custom-user-model

2023-10-19 21:44 UTC, NotMainCode commented on main/users/models.py
> +from django.contrib.auth.models import (
I001 isort found an import in the wrong position

расположить в одну строку
`from django.contrib.auth.models import AbstractUser`

2023-10-19 21:44 UTC, NotMainCode commented on main/users/models.py
> +from main.settings import MAX_LENGHT_USER_MODEL
Согласно [документации](https://docs.djangoproject.com/en/4.1/topics/settings/#using-settings-in-python-code) импорт должен быть `from django.conf import settings` и использование в данном случае - `settings.MAX_LENGHT_USER_MODEL`

2023-10-19 21:44 UTC, NotMainCode commented on main/users/models.py
> +class User(AbstractUser):
От `AbstractUser` унаследовано поле `username`, использование которого не предполагается в этом проекте

2023-10-19 22:11 UTC, NotMainCode commented on main/users/models.py
> +        verbose_name="Фамилия", max_length=MAX_LENGHT_USER_MODEL, blank=True, null=False
При таких значениях параметров `blank` и `null` нужно переопределять метод clean() - https://docs.djangoproject.com/en/4.2/ref/models/fields/#blank

Какова необходимость в `blank=True` для полей `last_name` и `email` ?

2023-10-19 22:12 UTC, NotMainCode commented on main/users/models.py
> +        verbose_name="Имя", max_length=MAX_LENGHT_USER_MODEL, blank=False, null=False
`blank=False, null=False` - значения по умолчанию, можно не указывать

2023-10-21 13:57 UTC, NotMainCode requested changes

2023-10-21 13:57 UTC, NotMainCode commented on main/users/user_manager.py
> +        user.is_admin = True
поля `is_admin` нет в модели `User` и в нём нет необходимости - удалить

2023-10-21 13:57 UTC, NotMainCode commented on main/users/models.py
> +        blank=False,
все поля обязательные и не могут иметь значение `Null` в БД
для полей `first_name` и `last_name` нужно или задать `blank=False, null=False` или удалить оба параметра (т.к. `False` это значение по умолчанию для этих параметров)

2023-10-21 13:57 UTC, NotMainCode commented on main/users/user_manager.py
> +"""User manager model module"""
D400 First line should end with a period

2023-10-21 13:57 UTC, NotMainCode commented on main/users/admin.py
> +        'first_name', 'last_name', 'email',
Q000 Single quotes found but double quotes preferred

заменить одиночные кавычки на двойные

2023-10-21 16:45 UTC, NotMainCode commented on main/users/user_manager.py
> +            self,
в строках 7-11 исправить отступ

2023-10-21 23:44 UTC, Stryukov reviewed
Поддерживаю комменты другого ревьюера. А зачем мы переопределяем модель юзера? Нам же стандартной для пользователя достаточно. Ничего нового мы не внесли в модель.

2023-10-22 10:00 UTC, aleksandrkomyagin commented on main/users/models.py
> +        blank=False,
Может я чего-то не понимаю, но если провалиться в AbstractUser, то у параметра blank по умолчанию True
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/112546606/1f38a0f1-b3c2-42f4-99b7-1f7ecd16ff93)

2023-10-22 11:17 UTC, NotMainCode approved these changes

2023-10-22 11:17 UTC, NotMainCode commented on main/users/models.py
> +        blank=False,
верно, моя ошибка - можно оставить только `blank=False` (`null=False` значение по умолчанию)

2023-10-26 21:38 UTC, Stryukov approved these changes

2023-10-27 21:01 UTC, NotMainCode requested changes

2023-10-27 21:01 UTC, NotMainCode commented on main/main/settings.py
> +MAX_LEN_FN_LN_USER_MODEL: int = 30
лучше `MAX_LEN_FULL_NAME_USER_MODEL`

2023-10-27 21:01 UTC, NotMainCode commented on main/users/models.py
> +        validator = CustomPasswordValidator()
не достаточно ли того, что валидатор указан в settings.py ?

2023-10-27 21:01 UTC, NotMainCode commented on main/users/validators.py
> +            "не более %(max_length)d символов. Разрешено использовать цифры и "
также разрешены буквы латинского алфавита в любом регистре

2023-10-27 21:01 UTC, NotMainCode commented on main/users/validators.py
> +    return (
нет необходимости возвращать True
в валидаторах либо вызвано исключение либо нет

2023-10-27 21:01 UTC, NotMainCode commented on main/users/validators.py
> +def raiser(e):
нет необходимости в этой функции

2023-10-28 08:36 UTC, aleksandrkomyagin commented on main/users/models.py
> +        validator = CustomPasswordValidator()
Если убрать валидацию из метода save(), то через админку все равно можно будет создать пользователя с невалидным паролем.

2023-10-28 18:58 UTC, NotMainCode approved these changes

2023-10-30 20:28 UTC, YarikineZ approved these changes

2023-10-30 20:28 UTC, YarikineZ commented on main/api/v1/urls.py
> +]
Мне нравится ваш подход к проектированию АПИ. Нормально Свагер генерируется?

2023-10-30 20:28 UTC, YarikineZ commented on main/users/validators.py
> +import re
1. А зачем вы написали свой валидатор для почты и пароля?
2. Кажется в будущем логика создания пользователя также должна уйти в API, чтобы фронт присылал только хэш. И тогда есть будет смысл валидировать на соответствие например SHA256

2023-10-30 20:36 UTC, NotMainCode commented on main/api/v1/urls.py
> +]
Свагер предполагаем генерировать с помощью drf-spectacular, инструмент обкатан в другом проекте - нравится )

2023-10-30 20:41 UTC, NotMainCode commented on main/users/validators.py
> +import re
1. Валидаторы реализованы согласно [ТЗ](https://github.com/Information-platform-about-IT-companies/Backend-main/wiki/%D0%9E%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE%D0%BB%D0%B5%D0%B9#%D0%BF%D0%BE%D0%BB%D0%B5-%D0%BF%D0%BE%D1%87%D1%82%D0%B0)
2. Да, пользователи будут создаваться через API. Сейчас предполагается, что пароль будет приходить как есть (в незашифрованном виде)

2023-10-30 20:48 UTC, merged

2023-11-01 08:45 UTC, YarikineZ commented on main/users/validators.py
> +import re
1. Ну, если есть отдельное ТЗ, от бизнеса окей
2. Передавать пароль в незашифрованном виде и хранить его таким в базе - очень плохая идея

2023-11-01 08:47 UTC, YarikineZ commented on main/api/v1/urls.py
> +]
Спасибо, записал себе

2023-11-04 07:20 UTC, NotMainCode commented on main/users/validators.py
> +import re
Пароль будет шифроваться и дешифроваться на стороне сервера, хранить будем в зашифрованном виде

2023-11-04 07:21 UTC, NotMainCode commented on main/users/validators.py
> +import re
Или лучше на фронте шифровать/дешифровать и передавать в зашифрованном виде?

2023-11-06 20:28 UTC, YarikineZ commented on main/users/validators.py
> +import re
Шифровать нужно на фронте. В бэк ни в каком случае не должен передаваться исходный пароль, только хэш

2023-11-06 20:49 UTC, NotMainCode commented on main/users/validators.py
> +import re
ок, спасибо