Feature/company-model
Information-platform-about-IT-companies/Backend-main pull request #5
Opened 2023-10-20 09:49 UTC by zemtsov-dm

Company model

2023-10-22 00:13 UTC, Stryukov requested changes
В целом все норм. А ТЗ у нас так не появилось? Где можно было посмотреть конкретизированные бизнес требования?

2023-10-22 00:13 UTC, Stryukov commented on main/companies/models.py
> +class Company(models.Model):
координаты на карте наверное надо добавить

2023-10-22 00:13 UTC, Stryukov commented on main/companies/models.py
> +    fields = models.CharField(max_length=200)  # Заглушка для модели Fields
что это за атрибут, не пойму? давай его по понятнее именуем. Судя по макету это услуги наверное. Как на счет services?

2023-10-23 22:13 UTC, NotMainCode requested changes

2023-10-23 22:13 UTC, NotMainCode commented on main/companies/models.py
> +    industries = models.CharField(max_length=200)  # Заглушка для модели Industries
создать модель `Industry` с одним полем `name - CharField` и связать с полем `industries`

2023-10-23 22:13 UTC, NotMainCode commented on main/companies/models.py
> +    fields = models.CharField(max_length=200)  # Заглушка для модели Fields
переименовать в `services` и связать с моделью `Service` в которой два поля - `name - CharField` и `category - FK ServiceCategory`. Модель `ServiceCategory` с одним полем `name - CharField`

2023-10-23 22:13 UTC, NotMainCode commented on main/companies/models.py
> +    logo = models.ImageField(upload_to="companiues/logo/")
`upload_to="companies/logo/"`

2023-10-23 22:13 UTC, NotMainCode commented on main/companies/models.py
> +    phones = models.TextField()  # Заглушка для модели Phones
этого поля не должно быть в модели `Company`, т.к. M2M связь с моделью `Phone` не корректна в данном случае
нужно создать модель `Phone` с двумя полями - `company - FK Company` и `phone - CharField`

2023-10-24 07:14 UTC, zemtsov-dm reviewed
Добавлены модели Industry,Phone,Service,ServiceCategory

2023-10-24 17:08 UTC, NotMainCode commented on main/companies/models.py
> +class Company(models.Model):
вроде пока не надо

2023-10-24 20:56 UTC, NotMainCode requested changes

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +    services = models.ForeignKey("Services", on_delete=models.CASCADE)
связь должна быть M2M
добавить `related_name="companies"`

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +    industries = models.ForeignKey(
связь должна быть M2M
добавить `related_name="companies"`

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +        Industry, on_delete=models.CASCADE, related_name="industries,"
`related_name="companies"`

https://techrocks.ru/2021/04/22/django-models-best-practices/

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE)
добавить `related_name="services"`

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
>      logo = models.ImageField(upload_to="companiues/logo/")
`companiues` исправить на `companies`

установить в venv Pillow и обновить `requirements.txtx`
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/421a8ba5-8833-4929-9e7f-3a20c3923ead)

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +    company = models.ForeignKey(Company, on_delete=models.CASCADE)
добавить `related_name="phones"`

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +class ServiceCategory(models.Model):
классы `ServiceCategory` и `Service` расположить перед классом `Company` - код будет читабельнее

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +    MinValueValidator,
I001 isort found an import in the wrong position

2023-10-24 20:56 UTC, NotMainCode commented on main/companies/models.py
> +    MaxLengthValidator,
I001 isort found an import in the wrong position

2023-10-25 12:42 UTC, NotMainCode requested changes

2023-10-25 12:42 UTC, NotMainCode commented on main/companies/models.py
> +        on_delete=models.CASCADE,
для M2M полей не применим параметр `on_delete`
![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/ecf4f6e5-10ca-4e7a-80d0-bffe72fb0333)

2023-10-25 12:42 UTC, NotMainCode commented on main/companies/models.py
> +        "Services",
нет модели `Services`, есть модель `Service`

модели `ServiceCategory` и `Service` расположить перед моделью `Company`, для поля `services` указать модель `Service` без кавычек

2023-10-25 12:42 UTC, NotMainCode commented on requirements.txt
73 новых зависимости - для чего они ?
оставить только те что нужны проекту

2023-10-25 12:44 UTC, NotMainCode requested changes
тестировать свой код перед отправкой на ревью - в данном случае нужно было пробовать сделать миграции

2023-10-25 13:16 UTC, zemtsov-dm reviewed
Внес правки

2023-10-25 14:08 UTC, NotMainCode approved these changes

2023-10-26 21:43 UTC, Stryukov approved these changes

2023-10-28 19:20 UTC, YarikineZ approved these changes

2023-10-29 15:27 UTC, merged