ci: test and build
Information-platform-about-IT-companies/Backend-main pull request #6
Opened 2023-10-27 04:51 UTC by Stryukov

Настроил шаг тестов и сборки. Сборка проходить не будет, пока секреты в настройки репозитория не положим. Тесты не проходят, там есть ошибки.

2023-10-27 16:53 UTC, NotMainCode requested changes

2023-10-27 16:53 UTC, NotMainCode commented on .github/workflows/main-develop.yml
> +on:
`on: [push]`
тесты должны запускаться при пуше в любую ветку, остальное при пуше в ветки develop | release | main

2023-10-27 16:53 UTC, NotMainCode commented on Dockerfile
> +RUN pip install gunicorn==20.1.0
нет необходимости - gunicorn есть в requirements.txt

2023-10-27 16:53 UTC, NotMainCode commented on Dockerfile
> +COPY ./main/ .
COPY . .

2023-10-27 19:26 UTC, Stryukov commented on Dockerfile
> +COPY ./main/ .
Объясни почему?

2023-10-28 17:22 UTC, NotMainCode commented on Dockerfile
> +COPY ./main/ .
в строке 3 создана папка `app` и осуществлён переход в неё
в строке 11 в папке `app` создаётся папка `main` в которую копируется всё из той папки где лежит докер-файл, получится `app/main/main/`

если указать `COPY . .` то получится структура `app/main/`

2023-10-29 21:26 UTC, Stryukov commented on Dockerfile
> +COPY ./main/ .
нет, как раз таки убираю этим самым папку main. Он в сборке не нужна. 
т.е. я копирую все с папки main репозитория в папку /app. Всеь проект будет лежать в папке app без папки main.

2023-10-29 21:30 UTC, Stryukov commented on .github/workflows/main-develop.yml
> +on:
Окей. Только у gihub actions есть ограничения на 2000 минут в месяц, надеюсь нам хватит. 
Тогда у бэка будет два workflow, один будет тесты запускать на каждый пуш в любой ветке. Второй будет запускать тести и собирать ветки при пул рекветсах в ветках develop и release. 
Я правильно предполагаю, что develop должен собираться в dev среде, а release уже в продакшене. Про main не понятно, его надо собирать? Если да, то зачем?

2023-11-06 01:01 UTC, Stryukov commented
Настроил 3 workflow, как обсуждали. Добавил шлюз (его правда только настроил для dev). Добавил конфиги docker compose.

2023-11-06 18:52 UTC, NotMainCode approved these changes

2023-11-06 18:56 UTC, aleksandrkomyagin approved these changes

2023-11-10 18:24 UTC, NotMainCode approved these changes

2023-11-11 22:00 UTC, closed without merging

2023-11-11 22:00 UTC, NotMainCode commented
Изменения в объединённом [PR](https://github.com/Information-platform-about-IT-companies/Backend-main/pull/13)