Feature/admin_panel
Information-platform-about-IT-companies/Backend-main pull request #8
Opened 2023-11-01 05:32 UTC by zemtsov-dm

Added admin panel

2023-11-01 13:30 UTC, NotMainCode requested changes
В админку невозможно войти.
Нужно:
- исправить вход
- на странице изменения данных пользователя обратить внимание на процесс изменения пароля

2023-11-04 05:06 UTC, Stryukov approved these changes

2023-11-08 00:49 UTC, aleksandrkomyagin commented
В модели `User` удали полностью метод `save` и импорт использованного класса.

2023-11-09 05:29 UTC, zemtsov-dm reviewed
Добавлен поиск в пользователях и ordering

2023-11-10 12:47 UTC, NotMainCode requested changes
в админку всё ещё невозможно войти

![image](https://github.com/Information-platform-about-IT-companies/Backend-main/assets/106552134/c125f255-4482-4acf-bf0d-525725a59763)

2023-11-10 12:47 UTC, NotMainCode commented on main/users/admin.py
> +    ordering = ('email',)
добавить пустую строку в конце файла

2023-11-10 14:50 UTC, zemtsov-dm reviewed
Fix проверки пароля в модели User, добавлена пустая строка в user admin

2023-11-10 21:29 UTC, NotMainCode approved these changes

2023-11-11 22:01 UTC, closed without merging

2023-11-11 22:01 UTC, NotMainCode commented
Изменения в объединённом [PR](https://github.com/Information-platform-about-IT-companies/Backend-main/pull/13)